# Dockerfile for Mongo Connector

# Use an official Python runtime as a parent image
FROM python:3.6-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
		ca-certificates \
		curl \
		netbase \
		wget \
	&& rm -rf /var/lib/apt/lists/*
	
RUN pip install mongo-connector==3.1.1 solr-doc-manager==0.1.0

COPY start_mongo_connector.sh /usr/local/bin
# RUN echo $(ls -lR)
ENTRYPOINT ["/usr/local/bin/start_mongo_connector.sh"]
CMD ["localhost", "localhost"]
