version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    # image: nhs-server
    # Using my local registry
    image: pjmd-ubuntu:5000/nhs-server-app:0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:5000"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  db:
    image: mongo:4.0.4
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - "/var/lib/mongodb:/data/db"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:

