version: "3"
# docker stack deploy -c docker-compose.yml nhs-app-stack
services:
  web:
    # replace username/repo:tag with your name and image details
    # image: nhs-server
    # Using my local registry
    image: pjmd-ubuntu:5001/nhs-server-app:v0.0.2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          # increased mem bc journalctl -k | grep -i -e memory -e oom showed on the remote some kills
          # see as well docker inspect <container ID>
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    environment:
      # nsh-server needs to know the db container host name in the overlay network. See: https://docs.docker.com/compose/networking/
      - MONGO_HOST=db
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  db:
    # https://gist.github.com/wesleybliss/29d4cce863f5964a3eb73c42501d99e4
    image: mongo:4.0.4
    # user: "${UID}:${GID}"
    # need user entry to prevent owner/group from being changed on the host to 999/mongodb container's user id
    user: "122:127"
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/stdout
    volumes:
      - "/var/lib/mongodb:/data/db"
    # need to add replication for MongoConnector: edit /etc/mongod.conf
    deploy:
      placement:
        constraints: [node.role == manager]
    command: --smallfiles 
    networks:
      - webnet
networks:
  # https://stackoverflow.com/questions/44647924/how-do-networking-and-load-balancer-work-in-docker-swarm-mode
  webnet:

